// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.network.http.http2.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "34d3a9d2-f94f-428d-9c41-9260a440a55f");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1655209207);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1655209205);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1655209200);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e2b65f05-073c-49cc-8444-46a694f81acd}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1655209203);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1655209208313");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1655230808313");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1655209205");
user_pref("browser.startup.homepage_override.buildID", "20210903235534");
user_pref("browser.startup.homepage_override.mstone", "92.0");
user_pref("browser.startup.lastColdStartupCheck", 1655209202);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1655209205135");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "92.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "f5de2f12e66b41d2bd171eee3e8f3fa3");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210903235534");
user_pref("extensions.lastAppVersion", "92.0");
user_pref("extensions.lastPlatformVersion", "92.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"80d7c168-645a-4d39-827a-e1fba33cf4b7\",\"formautofill@mozilla.org\":\"a24ad424-4120-4004-abff-711116038309\",\"pictureinpicture@mozilla.org\":\"015959df-69ae-4688-a054-254518a06993\",\"screenshots@mozilla.org\":\"72156bfc-ad4e-4195-b885-1ce399165b8e\",\"webcompat-reporter@mozilla.org\":\"249837cd-d7d5-41e0-8005-dd30adae5420\",\"webcompat@mozilla.org\":\"9f7b11df-f1d0-4ac6-9974-133325edd45f\",\"default-theme@mozilla.org\":\"deaeed6a-1c67-4e84-93ff-3f64b767f15a\",\"google@search.mozilla.org\":\"61d109f3-eb9f-4471-aa49-6474116e80b6\",\"wikipedia@search.mozilla.org\":\"b361e804-5d5a-4a57-870e-e9e1cddfe706\",\"bing@search.mozilla.org\":\"455fc264-ad45-413f-a58a-251ea8d55c84\",\"ddg@search.mozilla.org\":\"acd60b1d-caf5-4075-b874-fb4709fdd98e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1655209206);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3a6eda96-d9d3-4df1-ac40-00b1fdca9e20");
user_pref("toolkit.startup.last_success", 1655209199);
user_pref("toolkit.telemetry.cachedClientID", "2a3ff3e2-37eb-4b36-8fab-6909cafcefbc");
user_pref("toolkit.telemetry.previousBuildID", "20210903235534");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
